-- CLASE SABADO 07 OCTUBRE

 CREATE TABLE ALMACEN (NUMERO_ALMACEN INTEGER, 
                      UBICACION_ALMACEN VARCHAR2 (80),
                      CONSTRAINT PK_NA PRIMARY KEY(NUMERO_ALMACEN)
                      );