-- CLASE SABADO 07 OCTUBRE

 CREATE TABLE ALMACEN (NUMERO_ALMACEN INTEGER, 
                      UBICACION_ALMACEN VARCHAR2 (80),
                      CONSTRAINT PK_NA PRIMARY KEY(NUMERO_ALMACEN)
                      );
-- CREAR PROCEDIMIENTO ALMACENADO PARA GUARDAR UNA ENTIDAD O REGISTRO DE TIPO ALMACEN

CREATE OR REPLACE PROCEDURE GUARDAR_ALMACEN( MI_ID IN INTEGER, MI_UBICACION IN VARCHAR2 )
AS
BEGIN
-- AQUI VIENE LA LOGICA DEL PROCEDIMIENTO
INSERT INTO ALMACEN VALUES (MI_ID,MI_UBICACION);
END;
/

-- VAMOS A PROBAR QUE FUNCIONA NUESTRO PROCEDIMIENTO

BEGIN 
GUARDAR_ALMACEN(1,'PLYMOUTH');
END;
/

SELECT * FROM ALMACEN
