CREATE TABLE MAYORES (ID INTEGER PRIMARY KEY,
                      NOMBRE VARCHAR2(60),
                      EDAD INTEGER
                      );
                      
CREATE OR REPLACE TRIGGER DISP_MAYORES BEFORE INSERT ON MAYORES
FOR EACH ROW
BEGIN
 IF :NEW.EDAD<18 THEN  
 RAISE_APPLICATION_ERROR(-20000,'EDAD INCORRECTA');
 END IF;
END;
/

INSERT INTO MAYORES VALUES (1,'JUAN',20);
SELECT * FROM MAYORES;
INSERT INTO MAYORES VALUES (2,'ANA',16);

----------------------------------------------------

CREATE TABLE NOMINAS (ID INTEGER PRIMARY KEY,
                      SUELDO_BASE FLOAT,
                      HORAS_LABORADAS INTEGER,
                      DEPOSITO FLOAT
                      );
INSERT INTO NOMINAS VALUES (1,2000,20,28000);                                            
INSERT INTO NOMINAS VALUES (2,1000,16,50000);

CREATE OR REPLACE TRIGGER DISP_NOMINAS BEFORE UPDATE ON NOMINAS
FOR EACH ROW
BEGIN
 :NEW.DEPOSITO:=:OLD.DEPOSITO+:NEW.HORAS_LABORADAS*:OLD.SUELDO_BASE;
END;
/
SELECT * FROM NOMINAS;
UPDATE NOMINAS SET HORAS_LABORADAS=20 WHERE ID=1; 